#.travis.yml file


sudo: required
services: 
 - docker
 
before_install:
  - docker build -t name/of/file -f ./location/Dockerfile.dev .

script:
 - docker run dockerid/react-test npm test -- --coverage 
 
after_success:
 - docker build -t tagname/multi-client ./client
 - docker build -t tagname/multi-ngnix ./nginx
 - docker build -t tagname/multi-server ./server
 - docker build -t tagname/multi-worker ./worker
 
#LOG in to Docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 	

#PUSH images

- docker push dockerimage/name